### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ayasystems** [xypron/icsectl#1]
Hi

I don't know why but i need to send the follow command before use your library in order to work properly

echo -e "\x51\x00" > /dev/ttyUSB0

Do you know why?

Regards!

**Comment by xypron** [comment]
@ayasystems 

Did you set up the udev rule as described in README.rst?

The udev rule is needed to call icseudev when booting or when the relay card is plugged in.

icseudev sends 0x50 to determine the card type. If the card type is supported 0x51 0x00 is issued.

If this does not work for you, please, send the relevant part of the system log.

Best regards

Heinrich Schuchardt
