### ISSUE TITLE
PyPi package: project page links to pySISPM

### ISSUE THREAD

**Issue by SvenRoederer** [xypron/icsectl#3]
Just seen that the at https://pypi.org/project/icsectl/ the "Project-links" pointing to your https://github.com/xypron/pysispm project. 
Think this is by mistake.

**Comment by xypron** [comment]
Yes this looks wrong thanks.

**Comment by xypron** [comment]
Corrected in https://github.com/xypron/icsectl/commit/ea5eb2901ff70ea28dc3fd53a0e729582cffb0a0
